### ISSUE TITLE
Add verbose arg to sendAudio

### ISSUE THREAD

**Issue by ChristopherLucas** [ChristopherLucas/transcribeR#1]
sendAudio() uploads files. Add a 'verbose' argument (default TRUE) that when set to TRUE, prints out information while uploading. Like...

% Audio uploaded
[filename] successfully uploaded

Etc.

**Comment by ghost** [comment]
Sorry, do you mean % of all audio files uploaded, or % of a single file uploaded? We aren't sure if we can do the latter. Also, there exists a verbose() function. What precisely would the difference be between the existing verbose() function and the argument that you want?

**Comment by ChristopherLucas** [comment]
All files, but hold up on writing because sendAudio might change. Still writing a couple other issues - prob want to see them all before determining the order in which to complete them. 

verbose in httr just prints all this un-parsed stuff. We don't want that. We want sendAudio, which uploads a group of files (not just one) to tell users what's going on. 

Let me finish writing these other issues then I'll send you an example file.

**Comment by ghost** [comment]
Gotcha

**Comment by TmscanlanBoston** [comment]
Let me know when to add this. Is the best practice in R to use simple branching mechanisms like If/else statements for verbose mode?

**Comment by ChristopherLucas** [comment]
Yeah, branching is fine, thanks.
