### ISSUE TITLE
KOI8_R encoding generating problems interfacing with both APIs

### ISSUE THREAD

**Issue by mbenigni** [ChristopherLucas/transcribeR#6]
I am trying to translate Ukrainian and Russian hashtags.  The translation works in Google Sheets, but fails when I attempt to pass the data in the translate command.  I get the following error: 

Warning messages:
1: The content appears to be in UKRAINIAN-KOI8_R. However, the language code you provided suggests that the text is in
RUSSIAN. If you entered the wrong language code, stop the process. Otherwise, translateR will treat the text as
RUSSIAN. 
2: In curlSetOpt(..., .opts = .opts, curl = h, .encoding = .encoding) :
  Error setting the option for # 2 (status = 4) (enum = 10097) (value = 0x11ad48010): A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision. <not set>
Error in fromJSON(postForm("https://datamarket.accesscontrol.windows.net/v2/OAuth2-13",  : 
  error in evaluating the argument 'content' in selecting a method for function 'fromJSON': Error: Bad Request

A copy of the data is available at: https://docs.google.com/spreadsheets/d/14cCh_yl-148J5IPbKyKc2fapy_KNHyDMbU04zst9ItY/edit?usp=sharing

**Comment by ChristopherLucas** [comment]
(Note this is the transcribeR repo, not translateR)

Can you post the full code, scrubbing API keys?

Thanks,
Chris

**Comment by TmscanlanBoston** [comment]
Do you need me to do anything with this?
- Thomas Scanlan

Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by ChristopherLucas** [comment]
No, I think you're good, thanks Thomas!

**Comment by ChristopherLucas** [comment]
Matt, I'm closing this issue here because this is the wrong repo. Please create a new issue with the code you're using (API keys scrubbed) for translateR in the appropriate repo, link below. 

https://github.com/ChristopherLucas/translateR

Thanks again for using our software.

**Comment by mbenigni** [comment]
Thanks Chris. I will reopen in the correct repo
