### ISSUE TITLE
Error while applying transcibeR to convert wav file to text. 

### ISSUE THREAD

**Issue by vinay047** [ChristopherLucas/transcribeR#7]
Hi,
When we try to convert wav file to text we face the below error,

**Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) - The received certificate has expired.** 

**Please find the code i have used to convert**  

fnames <- 'English.wav '
#English.wav file was placed in the working directory C:/Users/prac
getwd()
C:/Users/prac
WAV_DIR <- getwd()
library(transcribeR)
print("First, printing language codes.")
printLanguages()
Sys.sleep(3)
print("Now posting requests to HP IDOL OnDemand's Speech Recognition API.")
CSV_LOCATION<-"C:/Users/prac/testfile.csv"
API_KEY<-"xxxxxxxxxxxxxxxx"
sendAudioGetJobs(wav.dir = WAV_DIR,
                 api.key = API_KEY,
                 interval = "-1",             # Transcript will not be segmented
                 encode = "multipart",
                 existing.csv = NULL,         # Intended to create a new CSV
                 csv.location = CSV_LOCATION,
                 language = "en-US",          # As printed above, one of the language codes
                 verbose = TRUE) 

Thanks in Advance!!

**Comment by ChristopherLucas** [comment]
This looks like an error related to your server and curl (
https://github.com/jeroen/curl/issues/127). Can you try it on a different
network? If it's your server, we probably can't debug this.

**Comment by vinay047** [comment]
How the program will recognize fnames <- 'English.wav '
**English.wav** file was placed in working directory.
Kindly helps us on this.

**Comment by ChristopherLucas** [comment]
I don't understand your question. What are you asking?

**Comment by vinay047** [comment]
Can u check is this the correct code and in **whole code we haven't used fnames.** Suggest us where we have to use fnames.
fnames <- 'English.wav '
**#English.wav file was placed in the working directory C:/Users/prac**
getwd()
C:/Users/prac
WAV_DIR <- getwd()
library(transcribeR)
print("First, printing language codes.")
printLanguages()
Sys.sleep(3)
print("Now posting requests to HP IDOL OnDemand's Speech Recognition API.")
CSV_LOCATION<-"C:/Users/prac/testfile.csv"
API_KEY<-"xxxxxxxxxxxxxxxx"
sendAudioGetJobs(wav.dir = WAV_DIR,
api.key = API_KEY,
interval = "-1", # Transcript will not be segmented
encode = "multipart",
existing.csv = NULL, # Intended to create a new CSV
csv.location = CSV_LOCATION,
language = "en-US", # As printed above, one of the language codes
verbose = TRUE)

**Comment by ChristopherLucas** [comment]
Hi vinay047,

In the example code, fnames is just pasted to the path for some example files, which are then locally downloaded for the example. 

I'm closing this as there's no issue raised.
